# Generated by Django 2.2.6 on 2020-06-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('League', '0001_initial'),
        ('Match', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.TextField(choices=[('TEAM1', 'TEAM1'), ('TEAM2', 'TEAM2'), ('TIE', 'TIE')])),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Match.Match')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
            ],
        ),
    ]
