# Generated by Django 2.2.1 on 2020-08-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pick', '0002_auto_20200704_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ['-MID__date', 'MID__order']},
        ),
    ]
