# Generated by Django 2.2.1 on 2020-09-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pick', '0003_auto_20200901_2243'),
        ('Pick', '0003_auto_20200818_2219'),
    ]

    operations = [
    ]
