# Generated by Django 2.2.1 on 2020-08-15 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crowd',
            fields=[
                ('ooid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('accounts', models.ManyToManyField(blank=True, to='Account.Account')),
            ],
        ),
    ]
