# Generated by Django 2.2.1 on 2020-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='GID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
