# Generated by Django 2.2.1 on 2020-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0002_auto_20200616_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leagueName',
            field=models.CharField(max_length=255),
        ),
    ]
