# Generated by Django 2.2.6 on 2020-06-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Participant', '0001_initial'),
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.TextField(choices=[('UPCOMING', 'UPCOMING'), ('CANCELLED', 'CANCELLED'), ('TEAM1', 'TEAM1'), ('TEAM2', 'TEAM2'), ('TIE', 'TIE')])),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Participant.Participant')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='Participant.Participant')),
            ],
        ),
    ]
