# Generated by Django 2.2.1 on 2020-09-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0003_auto_20200818_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date', 'order']},
        ),
        migrations.AddField(
            model_name='match',
            name='apiID',
            field=models.IntegerField(default=0),
        ),
    ]
