# Generated by Django 2.2.1 on 2020-08-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0003_auto_20200818_2159'),
        ('Match', '0003_auto_20200818_2140'),
    ]

    operations = [
    ]
