# Generated by Django 2.2.1 on 2020-08-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0004_merge_20200818_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date', 'order']},
        ),
    ]
