# Generated by Django 2.2.6 on 2020-06-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0002_auto_20200618_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
