# Generated by Django 2.2.1 on 2020-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0003_auto_20200618_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
